"""rename address

Revision ID: 749ad42a48ee
Revises: ee5e690d7682
Create Date: 2025-05-12 21:25:39.602206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749ad42a48ee'
down_revision = 'ee5e690d7682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
